"""init

Revision ID: 326ff30f90b3
Revises: dfcb69dd9724
Create Date: 2025-01-05 14:38:17.960818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '326ff30f90b3'
down_revision: Union[str, None] = 'dfcb69dd9724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sensors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('threshold_green', sa.Float(), nullable=False),
    sa.Column('threshold_yellow', sa.Float(), nullable=False),
    sa.Column('threshold_red', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_Sensors_id'), 'Sensors', ['id'], unique=False)
    op.create_index(op.f('ix_Sensors_mac_address'), 'Sensors', ['mac_address'], unique=True)
    op.create_table('SensorData',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sensor_id', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['Sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_SensorData_id'), 'SensorData', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SensorData_id'), table_name='SensorData')
    op.drop_table('SensorData')
    op.drop_index(op.f('ix_Sensors_mac_address'), table_name='Sensors')
    op.drop_index(op.f('ix_Sensors_id'), table_name='Sensors')
    op.drop_table('Sensors')
    # ### end Alembic commands ###
