"""add status column

Revision ID: af0c79009f09
Revises: 326ff30f90b3
Create Date: 2025-01-05 16:45:17.365859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af0c79009f09'
down_revision: Union[str, None] = '326ff30f90b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

status_choices_enum = sa.Enum('GREEN', 'YELLOW', 'RED', 'BLACK', name='statuschoices')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    status_choices_enum.create(op.get_bind())
    op.add_column(
        'Sensors',
        sa.Column('status', status_choices_enum, nullable=False, server_default='BLACK')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sensors', 'status')
    # ### end Alembic commands ###
